# Generated by Django 6.0.6 on 2026-06-17 00:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6,10}$', 'La cédula debe tener entre 6 y 10 dígitos.')])),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{7,10}$', 'El teléfono debe tener entre 7 y 10 dígitos.')])),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('especialidad', models.CharField(blank=True, max_length=60)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mecanico',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}\\d{3}$', 'Formato de placa inválido. Ejemplo: ABC123.')])),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='ordenes.cliente')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(editable=False, max_length=10, unique=True)),
                ('descripcion_problema', models.TextField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_DIAGNOSTICO', 'En diagnóstico'), ('COTIZADA', 'Cotizada'), ('EN_EJECUCION', 'En ejecución'), ('LISTA', 'Lista'), ('ENTREGADA', 'Entregada'), ('CERRADA_SIN_SERVICIO', 'Cerrada sin servicio')], default='RECIBIDA', max_length=25)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.cliente')),
                ('mecanico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.mecanico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.vehiculo')),
            ],
            options={
                'db_table': 'orden_servicio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
